const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');


module.exports = {
    mode: 'development',
    entry: {
      index: './src/scripts/index.js',  // Entry point for index.html
      about: './src/scripts/about.js',  // Entry point for about.html
      contact: './src/scripts/contact.js', // Entry point for contact.html
      blogs: './src/scripts/blogs.js',  // Entry point for blogs.html
      testimonials: './src/scripts/testimonials.js', // Entry point...
      services: './src/scripts/services.js', // Entry point....
      locations: './src/scripts/locations.js', // Entry point....
    },
    devtool: 'source-map',
    plugins: [
        new MiniCssExtractPlugin({
          filename: '[name].[contenthash].css',   // [name] will be replaced with the chunk name, such as main, page1, etc.
        }),
        new HtmlWebpackPlugin({ 
            template: './src/pages/index.html',
            favicon: './src/images/rwags-logo.ico',
            filename: 'index.html',
            inject: 'head',
            scriptLoading: 'defer',
            chunks: ['index'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/about.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'about/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['about'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/contact.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'contact/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['contact'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'blogs/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['blogs'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/testimonials.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'testimonials/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['testimonials'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/services/pressure-washing.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'pressure-washing/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['services'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/services/roof-gutter-clean.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'roof-gutter-clean/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['services'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/services/solar-panel-clean.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'solar-panel-clean/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['services'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/services/window-washing.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'window-washing/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['services'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/gutter-cleaning-pressure-washing-los-altos.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'gutter-cleaning-pressure-washing-los-altos/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/gutter-cleaning-services-atherton.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'gutter-cleaning-services-atherton/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/gutter-window-cleaning-redwood-city.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'gutter-window-cleaning-redwood-city/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/pressure-washer-gutter-cleaning-woodside.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'pressure-washer-gutter-cleaning-woodside/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/roof-gutter-cleaning-san-carlos.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'roof-gutter-cleaning-san-carlos/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/solar-panel-window-cleaning-menlo-park.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'solar-panel-window-cleaning-menlo-park/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/window-cleaning-pressure-washing-belmont.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'window-cleaning-pressure-washing-belmont/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/locations/window-gutter-cleaning-emerald-hills.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'window-gutter-cleaning-emerald-hills/index.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),

        // For all the blog pages
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/affordable-and-reliable-gutter-cleaning-service-near-me-that-delivers.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'affordable-and-reliable-gutter-cleaning-service-near-me-that-delivers.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/affordable-roof-and-gutter-cleaning-in-menlo-park-belmont.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'affordable-roof-and-gutter-cleaning-in-menlo-park-belmont.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/affordable-window-and-gutter-cleaning-services-in-redwood-city.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'affordable-window-and-gutter-cleaning-services-in-redwood-city.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/are-window-and-gutter-cleaning-near-me-worth-It.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'are-window-and-gutter-cleaning-near-me-worth-It.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/benefits-of-expert-window-washing-services-near-woodside.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'benefits-of-expert-window-washing-services-near-woodside.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/clear-views-clean-gutters-professional-home-care.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'clear-views-clean-gutters-professional-home-care.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/crystal-clear-views-window-cleaning-with-pressure-washing-in-belmont.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'crystal-clear-views-window-cleaning-with-pressure-washing-in-belmont.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/efficient-roofing-and-gutter-cleaning-in-emerald-hills.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'efficient-roofing-and-gutter-cleaning-in-emerald-hills.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/enhance-your-curb-appeal-with-expert-window-washing-services-in-menlo-park.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'enhance-your-curb-appeal-with-expert-window-washing-services-in-menlo-park.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/full-service-gutter-and-window-cleaning-services.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'full-service-gutter-and-window-cleaning-services.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/gutter-and-window-cleaning-in-woodside.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'gutter-and-window-cleaning-in-woodside.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/gutter-and-window-cleaning-services-in-redwood-city.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'gutter-and-window-cleaning-services-in-redwood-city.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/gutter-window-cleaning-services-why-rogers-windows-gutters-stands-out.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'gutter-window-cleaning-services-why-rogers-windows-gutters-stands-out.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/how-deep-cleaning-services-go-beyond-regular-cleaning.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'how-deep-cleaning-services-go-beyond-regular-cleaning.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/how-do-local-gutter-cleaning-services-help-prevent-costly-repairs-in-atherton.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'how-do-local-gutter-cleaning-services-help-prevent-costly-repairs-in-atherton.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/is-your-solar-panel-efficiency-slipping.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'is-your-solar-panel-efficiency-slipping.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/local-gutter-cleaning-in-atherton-clear-reliable-service.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'local-gutter-cleaning-in-atherton-clear-reliable-service.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/need-pressure-washing-services.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'need-pressure-washing-services.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/premium-gutter-cleaning-services-that-go-beyond-just-clearing-leaves.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'premium-gutter-cleaning-services-that-go-beyond-just-clearing-leaves.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/pressure-washing-services-in-menlo-park-refresh-exterior.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'pressure-washing-services-in-menlo-park-refresh-exterior.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/professional-gutter-cleaner-in-menlo-park.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'professional-gutter-cleaner-in-menlo-park.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/reliable-gutter-cleaning-service-in-emerald-hills.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'reliable-gutter-cleaning-service-in-emerald-hills.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/reliable-roof-and-gutter-cleaning-in-redwood-city.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'reliable-roof-and-gutter-cleaning-in-redwood-city.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/revitalize-space-expert-pressure-washing-services.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'revitalize-space-expert-pressure-washing-services.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/revive-your-home-with-expert-pressure-washing-services-in-atherton.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'revive-your-home-with-expert-pressure-washing-services-in-atherton.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/seasonal-window-gutter-cleaning-why-timing-matters.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'seasonal-window-gutter-cleaning-why-timing-matters.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/solar-panel-cleaning-service-how-it-enhances.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'solar-panel-cleaning-service-how-it-enhances.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/sparkling-clean-expert-window-washing-in-menlo-park.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'sparkling-clean-expert-window-washing-in-menlo-park.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/streak-free-living-starts-with-professional-window-washing-services.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'streak-free-living-starts-with-professional-window-washing-services.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/the-science-behind-sparkling-windows.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'the-science-behind-sparkling-windows.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/top-rated-professional-cleaners-near-you.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'top-rated-professional-cleaners-near-you.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/transform-business-commercial-window-cleaning-emerald-hills.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'transform-business-commercial-window-cleaning-emerald-hills.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/why-a-gutter-cleaning-company-is-a-must-have for-every-homeowner.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'why-a-gutter-cleaning-company-is-a-must-have for-every-homeowner.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/why-professional-cleaners-make-all-the-difference.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'why-professional-cleaners-make-all-the-difference.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/why-professional-commercial-window-cleaning-matters.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'why-professional-commercial-window-cleaning-matters.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
        new HtmlWebpackPlugin({ 
          template: './src/pages/blogs/why-redwood-city-homeowners-trust-this-solar-panel-cleaning-service-for-lasting-results.html',
          favicon: './src/images/rwags-logo.ico',
          filename: 'why-redwood-city-homeowners-trust-this-solar-panel-cleaning-service-for-lasting-results.html',
          inject: 'head',
          scriptLoading: 'defer',
          chunks: ['locations'],
        }),
    ],
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].bundle.js',
        clean: true,
    },
    module: {
        rules: [
          {
            test: /\.html$/i,
            use: ['html-loader'],  // Process image paths in HTML
          },
          {
            test: /\.css$/,
            use: [
              MiniCssExtractPlugin.loader,
              'css-loader',
            ],
          },
          {
            test: /\.(png|svg|jpg|jpeg|gif|ico)$/i,
            type: 'asset/resource',
          },
          {
            test: /\.(woff|woff2|eot|ttf|otf)$/i,
            type: 'asset/resource',
          },
        ],
      },
    optimization: {
      splitChunks: {
        chunks: 'all',
      },
    }, 
};